package elephantdocs

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path"
	"regexp"
	"slices"
	"strings"

	"github.com/Masterminds/semver/v3"
	"github.com/ttab/elephant-docs/internal"
)

// Protocol names that can be gated per API in the configuration.
const (
	ProtocolConnect = "connect"
	ProtocolTwirp   = "twirp"
)

// DefaultVendorRoot is where "mage rpc:vendorProto" copies protobuf files
// that a repository imports from another module. Its contents are compiled as
// imports, never documented as part of the repository's own APIs.
const DefaultVendorRoot = "rpc/vendor"

// protocolOrder is the order protocols are presented in, most current first.
var protocolOrder = []string{ProtocolConnect, ProtocolTwirp}

type Config struct {
	Modules []ModuleConfig     `json:"modules"`
	Schemas *SchemaGroupConfig `json:"schemas,omitempty"`
}

type SchemaGroupConfig struct {
	Title string            `json:"title"`
	Repo  string            `json:"repo"`
	Clone string            `json:"clone,omitempty"`
	Sets  []SchemaSetConfig `json:"sets"`
}

type SchemaSetConfig struct {
	Name  string `json:"name"`
	Title string `json:"title"`
	File  string `json:"file"`
}

type ModuleConfig struct {
	Title string `json:"title"`
	Name  string `json:"name"`
	Clone string `json:"clone,omitempty"`
	// ProtoRoot is the directory the module's API directories live in,
	// relative to the repository root. Empty means the repository root,
	// which is the original layout; a repository generated by the "rpc"
	// mage namespace can keep them under "rpc" instead.
	ProtoRoot string `json:"protoRoot,omitempty"`
	// VendorRoot is where the module vendors protobuf files it imports
	// from other modules. Defaults to DefaultVendorRoot.
	VendorRoot string                   `json:"vendorRoot,omitempty"`
	APIs       map[string]APIConfig     `json:"apis"`
	Include    map[string]IncludeConfig `json:"include,omitempty"`
}

// APIPath is the directory an API's protobuf files live in, relative to the
// repository root.
func (mc ModuleConfig) APIPath(api string) string {
	return path.Join(mc.ProtoRoot, api)
}

// VendorPath is the module's vendored proto root, relative to the repository
// root.
func (mc ModuleConfig) VendorPath() string {
	if mc.VendorRoot == "" {
		return DefaultVendorRoot
	}

	return path.Clean(mc.VendorRoot)
}

type APIConfig struct {
	Title string `json:"title"`
	// Protocols declares from and until which version of the module the
	// deployed service serves a protocol. An API without a "connect"
	// entry is documented as Twirp only.
	Protocols map[string]ProtocolConfig `json:"protocols,omitempty"`

	// gates are the parsed and validated Protocols, in protocolOrder.
	// Populated by Config.Validate so that a malformed version fails the
	// build instead of quietly producing a Twirp-only site.
	gates []protocolGate
}

type ProtocolConfig struct {
	// From is the first module version whose deployed service serves the
	// protocol. An unset From on a declared protocol means "always".
	From string `json:"from,omitempty"`
	// Until is the first module version whose deployed service no longer
	// serves the protocol.
	Until string `json:"until,omitempty"`
	// Note is rendered next to the protocol on the pages that offer it.
	Note string `json:"note,omitempty"`
}

// protocolGate is a parsed ProtocolConfig.
type protocolGate struct {
	Name     string
	FromTag  string
	From     *semver.Version
	UntilTag string
	Until    *semver.Version
	Note     string
}

type IncludeConfig struct {
	From string `json:"from"`
}

// LoadConfig reads and validates the site configuration. Unknown fields are
// rejected so that a misspelled key fails the build rather than being
// silently ignored.
func LoadConfig(configPath string) (_ Config, outErr error) {
	var conf Config

	f, err := os.Open(configPath)
	if err != nil {
		return Config{}, fmt.Errorf("open config file: %w", err)
	}

	defer internal.Close("config file", f, &outErr)

	dec := json.NewDecoder(f)

	dec.DisallowUnknownFields()

	err = dec.Decode(&conf)
	if err != nil {
		return Config{}, fmt.Errorf("unmarshal config: %w", err)
	}

	err = conf.Validate()
	if err != nil {
		return Config{}, fmt.Errorf("invalid config: %w", err)
	}

	return conf, nil
}

var relPathExp = regexp.MustCompile(`^[a-zA-Z0-9_.-]+(/[a-zA-Z0-9_.-]+)*$`)

// Validate checks the configuration and parses the values that are cheaper to
// parse once than once per rendered page.
func (c *Config) Validate() error {
	if len(c.Modules) == 0 {
		return errors.New("no modules configured")
	}

	seen := make(map[string]string)

	for i := range c.Modules {
		mod := &c.Modules[i]

		if mod.Name == "" {
			return fmt.Errorf("module %d: missing name", i)
		}

		if len(mod.APIs) == 0 {
			return fmt.Errorf("module %q: no APIs configured", mod.Name)
		}

		err := validateRoot("protoRoot", mod.ProtoRoot)
		if err != nil {
			return fmt.Errorf("module %q: %w", mod.Name, err)
		}

		err = validateRoot("vendorRoot", mod.VendorRoot)
		if err != nil {
			return fmt.Errorf("module %q: %w", mod.Name, err)
		}

		for api, apiConf := range mod.APIs {
			other, duplicate := seen[api]
			if duplicate {
				return fmt.Errorf(
					"the API %q is declared by both %q and %q",
					api, other, mod.Name)
			}

			seen[api] = mod.Name

			if apiConf.Title == "" {
				return fmt.Errorf("API %q: missing title", api)
			}

			gates, err := parseProtocolGates(apiConf.Protocols)
			if err != nil {
				return fmt.Errorf("API %q: %w", api, err)
			}

			apiConf.gates = gates

			mod.APIs[api] = apiConf
		}

		for api, inc := range mod.Include {
			if inc.From == "" {
				return fmt.Errorf(
					"module %q: include %q: missing source module",
					mod.Name, api)
			}
		}
	}

	if c.Schemas != nil && c.Schemas.Repo == "" {
		return errors.New("schemas: missing repo")
	}

	return nil
}

func validateRoot(name string, root string) error {
	if root == "" {
		return nil
	}

	if !relPathExp.MatchString(root) {
		return fmt.Errorf(
			"%s %q must be a relative slash separated path", name, root)
	}

	if root == ".." || strings.HasPrefix(root, "../") {
		return fmt.Errorf("%s %q must not leave the repository", name, root)
	}

	return nil
}

func parseProtocolGates(
	protocols map[string]ProtocolConfig,
) ([]protocolGate, error) {
	if len(protocols) == 0 {
		return nil, nil
	}

	gates := make([]protocolGate, 0, len(protocols))

	for name, pc := range protocols {
		if !slices.Contains(protocolOrder, name) {
			return nil, fmt.Errorf(
				"unknown protocol %q, expected one of %s",
				name, strings.Join(protocolOrder, ", "))
		}

		gate := protocolGate{
			Name:     name,
			FromTag:  pc.From,
			UntilTag: pc.Until,
			Note:     pc.Note,
		}

		if pc.From != "" {
			v, err := semver.NewVersion(pc.From)
			if err != nil {
				return nil, fmt.Errorf(
					"protocol %q: invalid from version %q: %w",
					name, pc.From, err)
			}

			gate.From = v
		}

		if pc.Until != "" {
			v, err := semver.NewVersion(pc.Until)
			if err != nil {
				return nil, fmt.Errorf(
					"protocol %q: invalid until version %q: %w",
					name, pc.Until, err)
			}

			gate.Until = v
		}

		if gate.From != nil && gate.Until != nil &&
			!gate.From.LessThan(gate.Until) {
			return nil, fmt.Errorf(
				"protocol %q: from %q is not before until %q",
				name, pc.From, pc.Until)
		}

		gates = append(gates, gate)
	}

	slices.SortFunc(gates, func(a, b protocolGate) int {
		return slices.Index(protocolOrder, a.Name) -
			slices.Index(protocolOrder, b.Name)
	})

	return gates, nil
}

// gate returns the parsed gate for a protocol, if the API declares one.
func (ac APIConfig) gate(name string) (protocolGate, bool) {
	for _, g := range ac.gates {
		if g.Name == name {
			return g, true
		}
	}

	return protocolGate{}, false
}
